# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
    application:
        name: securityalarm
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jackson:
        serialization.write_dates_as_timestamps: false
        time-zone: GMT+3
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    cache:
            jcache:
                config: config/ehcache.xml
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
        async:
              request-timeout: -1
    thymeleaf:
        mode: XHTML
    http:
      multipart:
        enabled: true

security:
    basic:
        enabled: false
    oauth2:
        resource:
            filter-order: 3


server:
    session:
        cookie:
            http-only: true


# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    security:
            authentication:
                oauth:
                    clientid: securityalarmapp
                    secret:
            sms:
                url: http://api.txtlocal.com/bulk_json
                apikey: qp7CsPtLRvY-vtgvb8KgGwCNzVnaKCYdAFcvGZfyyL
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    #cors: #By default CORS are not enabled. Uncomment to enable.
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: no-reply@securityalarm.com
    swagger:
        title: securityalarm API
        description: securityalarm API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
    ribbon:
        # comma separated list of profiles to show a ribbon on the GUI
        displayOnActiveProfiles: dev
